MVC_AdopterUnDev/Controllers/Client01Controller.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AdopteUnDev_Common.IRepositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVC_AdopterUnDev.Models;

namespace MVC_AdopterUnDev.Controllers
{
    public class Client01Controller : Controller
    {
        private readonly IDeveloperRepository<BLL_AdopteUnDev01.Models.Client> _serviceCl;
        public Client01Controller(IDeveloperRepository<BLL_AdopteUnDev01.Models.Client> serviceCl)
        {
            this._serviceCl = serviceCl;
        }

        // cadi sulla pag dove hai o login o registrati: vista parziale di action Login
        public ActionResult Index()
        {
            return View();
            //return PartialView(); //ritorna solo view 'index.cshtml' SENZA _layout
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ClientIndex collection)
        {

            try
            {
                //if (result is null) throw new Exception("Nessun developer con questo identificante");
                if (!ModelState.IsValid) throw new Exception();
                if (!collection.Validate) throw new Exception("Bisogna validare la cancellazione!");

                return RedirectToAction(nameof(Index), "Developer");

            }
            catch (Exception)
            {

                return RedirectToAction(nameof(Index));
            }
        }

        public ActionResult Login()
        {
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(ClientLogin collection)
        {
            try
            {
                return RedirectToAction("Index", "Developer");
            }
            catch (Exception)
            {

                throw;
            }
        }





        // GET: ClientController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClientController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClientController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClientController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ClientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClientController/Delete/5
        //NON dimenticare che non cancella i clienti; ma loro 'login' e 'psw' !!
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClientController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC_AdopterUnDev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_AdopterUnDev</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <figure>
                    <img src="~/assets/logoAdopte.png" alt="logo" />
                </figure>
            </div><br />
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Developer" asp-action="Index">MVC_AdopterUnDev</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Developer" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client01" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_AdopterUnDev - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>